const themeSwapper = require('tailwindcss-theme-swapper');

const dark = {
  body: '#222',
  'alt-body': '#303030',
  border: '#444',
  't-divder': '#e1e2e3',
  grey: '#888',
  primary: '#2fc6e4, ',
  'h-primary': '#072b46',
  secondary: '#444',
  'h-secondary': '#3A3A3F',
  tertiary: '#375a7f',
  'h-tertiary': '#2f4d6c',
  success: '#1a7051',
  'h-success': '#00a077',
  info: '#3498db',
  'h-info': '#2c81ba',
  danger: '#e53e3e',
  'h-danger': '#e74c3c',
  warning: '#f98904',
  'h-warning': '#cf850f',
  light: '#adb5bd',
  'h-light': '#939aa1',
  dark: '#303030',
  'h-dark': '#292929',
  form: '#222',
  'body-color': '#fff',
  'notify-red': ' #c00',
  darker: ' #0e1924',
  'darker-dark': ' #010e1c',
  'not-so-dark': ' #223244',
  blue: ' #2196f3',
  'state-blue': ' #1da1f2',
  prematch: ' #662e50',
  'in-play': ' #662e2e',
  virtuals: ' #895246',
  'light-grey': ' #dadada',
  'light-dark': ' #a8bacb',
  'lemon-grey': ' #55705a',
  'green-grey': ' #214143',
  'deep-yellow': ' #fe9924',
  'dark-grey': ' #696969',
  'not-so-grey': ' #c4c4c4',
  'primary-green': ' #1a7051',
  'soft-green': ' #6cb54a',
  'primary-yellow': ' #edb941',
  'not-so-yellow': ' #deb886',
  'primary-dark': ' #1a2633',
  'primary-light-dark': ' #343e49',
  'primary-red': ' #c83200',
  'light-red': ' #f81d1d',
  'deep-red': ' #8c2027',
  'primary-text': ' #1a1b1b',
  'secondary-light': ' #ffe684',
  'secondary-dark': ' #fee5bb',
  'secondary-text': ' #a8bacb',
  'secondary-not-so-dark': ' #283441',
  'light-green': ' #c1ffdd',
  brown: ' #895246',
  'text-primary': '#0e1924',
  'text-secondary': '#a8bacb',
  'text-tertiary': '#edb941',
  'text-default': ' #fff',
  'text-alternate': '#1d2f66',
  'text-secondary-alternate': '#a8bacb',
  'odds-default': '#0e1924',
  'odds-active': '#deb886',
  divider: ' #495b6f',
  'border-secondary': ' #223244',
  'border-tertiary': ' #a5aeb8  ',
  'border-alternate': '#edb941',
  'border-betslip': ' #1a2633',
  'button-primary': '#edb941',
  'button-secondary': '#deb886',
  'button-tertiary': '#36233c',
  'button-alternate': '#343e49',
  'button-secondary-alternate': '#283441',
  // 'bg-primary': '#1a2633',
  'bg-primary': '#1c1224',
  'bg-secondary': '#0e1924',
  'bg-tertiary': '#3c2943',
  'bg-alternate': '#283441',
  'bg-secondary-alternate': '#3a2a43',
  'bg-statistics': '#283441',
  'bg-featured-top': '#55705a',
  'bg-featured-base': ' #213243',
  'text-featured-camp': '#dadada',
  'text-featured-score': '#c1ffdd',
  'card-bg': '#343e49',
  'input-bg': '#BA85C433',
  'navbar-bg': '#1a2633',
  'drawer-bg': ' #213243',
  'accordion-bg': ' #0e1924',
  'firebet-bg': '#0e1924',
  'message-bg': ' #8d6d21',
  'table-bg': '#f8f1ff',
  switcher: '#464040',
  icon: '#c5cfd5',
  sidebar: '#1d2f66',
};

const base = {
  body: '#fff',
  'alt-body': '#fff',
  border: '#ecf0f1',
  't-divider': '#dee2e6',
  grey: '#444',
  primary: '#1d2f66',
  'h-primary': '#2fc6e4',
  secondary: '#dd4f46',
  'h-secondary': '#a8453e',
  tertiary: '#a8238a',
  'h-tertiary': '#b84c9e',
  info: '#3498db',
  'h-info': '#2c81ba',
  info: '#3498db',
  'h-info': '#2c81ba',
  dark: '#303030',
  warning: '#f98904',
  'h-warning': '#cf850f',
  success: '#48bb78',
  'h-success': '#00a077',
  danger: '#f56565',
  'h-danger': '#c44133',
  light: '#ecf0f1',
  'h-light': '#eff2f3',
  dark: '#7b8a8b',
  'h-dark': '#697576',
  form: '#ced4da',
  'body-color': '#212529',
  'text-primary': '#fff',
  'text-secondary': '#343e49',
  'text-tertiary': '#010e1c',
  'text-default': '#0e1924',
  'text-alternate': '#1d2f66',
  'text-secondary-alternate': '#343e49',
  'odds-default': '#e8f3ff',
  'odds-active': '#063c67',
  divider: '#a8bacb',
  'border-secondary': '#e8f3ff',
  'border-tertiary': '#a8bacb',
  'border-alternate': '#0e1924',
  'border-betslip': '#a8bacb',
  'button-primary': '#edb941',
  'button-secondary': '#deb886',
  'button-tertiary': '#e2b6d3',
  'button-alternate': '#edb941',
  'button-secondary-alternate': '#e8f3ff',
  'bg-primary': '#fff',
  'bg-secondary': '#063c67',
  'bg-tertiary': '#1979a9',
  'bg-alternate': '#f5f5f5',
  'bg-secondary-alternate': '#1979a9',
  'bg-statistics': '#a8bacb',
  'bg-featured-top': '#f3fff5',
  'bg-featured-base': '#55705a',
  'text-featured-camp': '#283441',
  'text-featured-score': '#283441',
  'card-bg': '#e8f3ff',
  'primary-green': ' #1a7051',
  'table-bg': '#f8f1ff',
  darker: ' #0e1924',
  icon: '#343e49',
  'icon-bg': '#ebebeb',
};

// hints
// default color = text-color

module.exports = {
  important: true,
  purge: [],
  theme: {
    fontFamily: {
      primary: ['Open Sans', 'sans-serif'],
      secondary: ['Open Sans', 'sans-serif'],
    },
    extend: {
      width: {
        15: '15.7rem',
        '3/20': '15%',
        '3/25': '12%',
        '2/25': '8%',
        '1/25': '4%',
        '0.5/25': '2%',
        '4/25': '16%',
        '7/50': '14%',
        450: '28.125rem',
      },
      height: {
        7: '28px',
        20: '20rem',
      },
      transformOrigin: {
        0: '0%',
      },
      zIndex: {
        '-1': '-1',
      },
      screens: {
        print: { raw: 'print' },
        // => @media print { ... }
      },
    },
  },
  variants: {},
  plugins: [
    themeSwapper({
      themes: [
        // The only required theme is `base`. Every property used in
        // other themes must exist in here.
        {
          name: 'base',
          selectors: [':root'],
          theme: {
            colors: {
              primary: {
                'm-body': base['body'],
                'alt-body': base['alt-body'],
                'm-border': base['border'],
                't-divider': base['t-divider'],
                'm-grey': base['grey'],
                'm-primary': base['primary'],
                'h-primary': base['h-primary'],
                'm-secondary': base['secondary'],
                'h-secondary': base['h-secondary'],
                'm-tertiary': base['tertiary'],
                'h-tertiary': base['h-tertiary'],
                'm-success': base['success'],
                'h-success': base['h-success'],
                'm-info': base['info'],
                'h-info': base['h-info'],
                'm-danger': base['danger'],
                'h-danger': base['h-danger'],
                'h-warning': base['h-warning'],
                'm-warning': base['warning'],
                'm-light': base['light'],
                'h-light': base['h-light'],
                'm-dark': base['dark'],
                'h-dark': base['h-dark'],
                'm-form': base['form'],
                'body-color': base['body-color'],
                bg: base['bg-primary'],
                text: '#333',
                alternate: base['text-alternate'],
                'bg-sec': base['bg-secondary'],
                'bg-ter': base['bg-tertiary'],
                text: base['text-priamry'],
                tertiary: base['text-tertiary'],
                'default-main': base['text-default'],
                secondary: base['text-secondary'],
                'secondary-alt': base['text-secondary-alternate'],
                divider: base['divider'],
                accordion: base['accordion-bg'],
                card: base['card-bg'],
                'featured-score': base['text-featured-score'],
                'featured-top': base['bg-featured-top'],
                'featured-base': base['bg-featured-base'],
                statistics: base['bg-statistics'],
                button: base['button-primary'],
                'button-tet': base['button-primary'],
                'button-sec': base['button-secondary'],
                'button-alt': base['button-alternate'],
                'button-sec-alt': base['button-secondary-alternate'],
                grey: base['grey'],
                input: dark['input-bg'],
                green: base['primary-green'],
                'btn-tert': base['button-tertiary'],
                border: base['border-tertiary'],
                'border-sec': base['border-secondary'],
                'table-light': base['table-bg'],
                'notify-red': base['notify-red'],
                darker: base['darker'],
                switcher: dark['switcher'],
                icon: base['icon'],
                'icon-bg': base['text-default'],
                table: base['table-bg'],
                sidebar: dark['sidebar'],
                event: base['button-tertiary'],
                'sec-alt': base['bg-secondary-alternate'],
              },
            },
          },
        },
        {
          name: 'dark',
          selectors: ['.dark'],
          mediaQuery: '@media (prefers-color-scheme: dark)',
          theme: {
            colors: {
              primary: {
                'm-body': dark['body'],
                'alt-body': dark['alt-body'],
                'm-border': dark['border'],
                't-divider': dark['t-divider'],
                'm-grey': dark['grey'],
                'm-primary': base['primary'],
                'h-primary': dark['h-primary'],
                'm-secondary': dark['secondary'],
                'h-secondary': dark['h-secondary'],
                'm-tertiary': dark['tertiary'],
                'h-tertiary': dark['h-tertiary'],
                'm-success': dark['success'],
                'h-success': dark['h-success'],
                'm-info': dark['info'],
                'h-info': dark['h-info'],
                'm-danger': dark['danger'],
                'h-danger': dark['h-danger'],
                'h-warning': dark['h-warning'],
                'm-warning': dark['warning'],
                'm-light': dark['light'],
                'h-light': dark['h-light'],
                'm-dark': dark['dark'],
                'h-dark': dark['h-dark'],
                'm-form': dark['form'],
                'body-color': dark['body-color'],
                bg: dark['bg-primary'],
                text: '#fff',
                alternate: dark['text-alternate'],
                'bg-sec': dark['bg-secondary'],
                'bg-ter': dark['bg-tertiary'],
                text: dark['text-priamry'],
                tertiary: dark['text-tertiary'],
                'default-main': dark['text-default'],
                secondary: dark['text-secondary'],
                'secondary-alt': dark['text-secondary-alternate'],
                divider: dark['divider'],
                accordion: dark['accordion-bg'],
                card: dark['card-bg'],
                'featured-score': dark['text-featured-score'],
                'featured-top': dark['bg-featured-top'],
                'featured-base': dark['bg-featured-base'],
                statistics: dark['bg-statistics'],
                button: dark['button-primary'],
                'button-tet': dark['button-primary'],
                'button-sec': dark['button-secondary'],
                'button-alt': dark['button-alternate'],
                'button-sec-alt': dark['button-secondary-alternate'],
                input: dark['bg-tertiary'],
                'btn-tert': dark['button-tertiary'],
                border: dark['border-tertiary'],
                'table-light': dark['table-bg'],
                'border-sec': base['border-secondary'],
                'notify-red': dark['notify-red'],
                darker: dark['darker'],
                switcher: dark['switcher'],
                icon: dark['icon'],
                'icon-bg': dark['icon-bg'],
                table: base['table-bg'],
                sidebar: dark['sidebar'],
                event: dark['sidebar'],
                'sec-alt': dark['bg-secondary-alternate'],
              },
            },
          },
        },
      ],
    }),
  ],
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
};
