export const state = () => ({
  featuredCars: [
    {
      img: 'img/car/car-1.jpg',
      make: 'Lamborghini',
      price: '$1050.00',
      model: '2.2L XLS 4x2 MT',
      type: 'For Sale',
      bodyStyle: 'Covertible',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          way: '4,000 km',
          transmission: 'Manual',
          car: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
    {
      img: 'img/car/car-2.jpg',
      make: 'Ferrari Red Car',
      price: '$780.00',
      model: '2.2L XLS 4x2 MT',
      type: 'Featured',
      bodyStyle: 'Covertible',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          speed: '4,000 km',
          transmission: 'Manual',
          carType: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
    {
      img: 'img/car/car-3.jpg',
      make: 'Bmw e46 m3 Diski Serie',
      price: '$$940.00',
      model: '2.2L XLS 4x2 MT',
      type: 'For Rent',
      bodyStyle: 'Covertible',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          way: '4,000 km',
          transmission: 'Manual',
          car: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
    {
      img: 'img/car/car-4.jpg',
      make: 'Volkswagen Scirocco',
      price: '$1050.00',
      model: '2.2L XLS 4x2 MT',
      type: 'Featured',
      bodyStyle: 'Sedan',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          way: '4,000 km',
          transmission: 'Manual',
          car: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
    {
      img: 'img/car/car-5.jpg',
      make: 'Porsche Cayen Last',
      price: '$780.00',
      model: '2.2L XLS 4x2 MT',
      type: 'For Sale',
      bodyStyle: 'Covertible',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          way: '4,000 km',
          transmission: 'Manual',
          car: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
    {
      img: 'img/car/car-6.jpg',
      make: 'Lexus GS F',
      price: '$940.00',
      model: '2.2L XLS 4x2 MT',
      type: 'Featured',
      bodyStyle: 'Covertible',
      condition: 'Brand New',
      mileage: '34,000 mi',
      interiorColor: 'Dark Grey',
      engine: '3.4L Mid-Engine V6',
      gears: '5',
      specifications: [
        {
          fuelType: 'Petrol',
          way: '4,000 km',
          transmission: 'Manual',
          car: 'Sport',
          gear: 'Blue',
          year: '2022',
          horsePower: '310',
          topSpeed: '270',
          driveTrain: 'Front Wheel',
          doors: '4',
          location: 'Lagos, Nigeria',
          bodyStyle: 'Sedan',
        },
      ],
      features: [
        'Cruise Control',
        'Airbags',
        'Air Conditioning',
        'Alarm System',
        'Audio Interface',
        'CDR Audio',
        'Seat Heating',
        'Park Assist',
        'Automatic Climate Control',
        'Auto Start/Stop',
      ],
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar.Donec a consectetur nulla. Nulla posuere sapien vitae lectus suscipit, e pulvinar nisi tincidunt. Aliquam erat volutpat. Curabitur convallis fringilla diam sed aliquam. Sed tempor iaculis massa faucibus feugiat. In fermentum facilisis massa, a consequat purus viverra a. Aliquam pellentesque nibh et nibh feugiat gravida. Maecenas ultricies, diam vitae semper placerat, velit risus accumsan nisl, eget tempor lacus est vel nunc. Proin accumsan elit sed neque euismod fringilla. Curabitur lobortis nunc velit, et fermentum urna dapibus non. Vivamus magna lorem, elementum id gravida ac, laoreet tristique augue. Maecenas dictum lacus eu nunc porttitor, ut hendrerit arcu efficitur.',
    },
  ],
  car: {},
});

export const getters = {
  getFeaturedCars(state) {
    return state.featuredCars;
  },

  getCar(state) {
    return state.car;
  },
};

export const mutations = {
  setFeaturedCars(state, value) {
    return (state.featuredCars = value);
  },

  setCar(state, value) {
    return (state.car = value);
  },
};

export const actions = {};
