apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretsName }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.registryAuth }}
type: kubernetes.io/dockerconfigjson
