kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ include "helm-chart.fullname" . }}-deployer'
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ['', 'extensions', 'apps']
    resources: ['*']
    verbs: ['*']
